version: '3'

# TODO web and worker need to be in here as well. Postgres was first to make dev work easier.
services:
  postgres:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "127.0.0.1:5432:5432"
    restart: always

volumes:
  db-data:
